### PR TITLE
Remote webroot validation SSH connection caching

### LINKED ISSUE #25: Cache SSH connections
The remote webroot feature could cache its connections for the case where a single wile run is supposed to generate certificates for many domains on the same ssh host.

### PR DESCRIPTION
**Pull request by lumatijev**
Tested and everything works as expected.

Comparing secure log before and after changes shows that connection is cached. 

Closes #25

### CODE REVIEW

**Comment by lumatijev** [comment]
Travis CI tests are failing because of flake8 complexity test:
./wile/cert.py:46:1: C901 'request' is too complex (18)

I can try to reduce request function or we could increase `--max-complexity` option for flake8.

**Comment by lumatijev** [comment]
@costela Any info about this?

**Comment by costela** [comment]
Hi, sorry for the delay. As I opened the issue, I already had a rough idea how I wanted to implement it, and wanted to give it a try over the weekend. Unfortunately I didn't have quite as much time as I wanted, so I'll probably still need a few days.

My main issue with the approach in this PR is the use of globals and the interweaving of the caching with the actual "work" being done. I'd rather have it completely encapsulated away. This would probably be helpful in the future, if I ever get around to implementing parallel operations.

I'm still grateful for the contribution, though! Just give me a few more days to consider the different approaches.

**Comment by costela** [comment]
I added a new commit fixing the issue in a way that seems a bit cleaner (not adding more complexity to existing functions). So I think this one will have to be rejected 😕 
But thanks for the help anyway! 👍

**Pull request closed without merging**
